### ISSUE TITLE
add initialize sync method using spawn sync

### ISSUE THREAD

**Issue by elyseholladay** [RetailMeNotSandbox/roux#22]
this returns a deserialized pantry instance

**Comment by lzilioli** [comment]
I'm working on this in a local branch and have run into a couple of issues cc/ @knksmith57 any thoughts here?

I have not yet written the code to revive a pantry from a POJO given that I want to ensure everything else is going to work properly first.

**blocking**

- This approach relies on the ability to `JSON.stringify` the `config` we pass to initialize. Because the config can contain predicates that are either `function`s or `regex`es, the config can not properly be serialized to pass to the child process.

**non-blocking**

- I was going to test by wrapping the `initializeSync` method in a function that returns a promise, to avoid having to refactor the test code to land this change. Problem is, the pantry directories generated by mockfs live in the parent process to the child process spawned from `initializeSync`. Thus `initializeSync` can't see these files.
  - I think this can be addressed by mocking `spawnSync` for the test such that initialize is invoked in the parent process for purposes of testing.

**Comment by lzilioli** [comment]
A supported format for webpack.config.js is to `module.export` a function which returns a promise. Within this method, you can perform async initialization logic before resolving the promise with the webpack config.

I believe this fact obviates the need for an `initializeSync` method.

@lawnsea, @knksmith57 does this make sense to y'all?
